### ISSUE TITLE
Missing file: "Kitsunebi_Tests" and "alpha.mp4"

### ISSUE THREAD

**Issue by qq345386817** [noppefoxwolf/Kitsunebi#1]

**Comment by noppefoxwolf** [comment]
Thanks!!
I fixed this issue.
https://github.com/noppefoxwolf/Kitsunebi/commit/2119e82c29cd8950b17ea4e9f82d3806eb9d2654

and..

main.mp4 and alpha.mp4 are downloaded by yourself.
if you don't have this files, for example download from this link.
http://basic.ivory.ne.jp

This issue will close.
If you found more or other one. please open new issue.
